apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mrinank/auth:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: auth-secret
              mountPath: /main_app/secrets
              readOnly: true
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MYSQL_DB
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MYSQL_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
      volumes:
        - name: auth-secret
          secret:
            secretName: auth-secret
