name: Publish Docker Images

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_STOP }}
          password: ${{ secrets.DOCKER_PAT_STOP }}
        
      - name: Build and push auth image
        run: |
          if git diff --quiet HEAD -- ./auth; then
            echo "No changes detected in ./auth"
          else
            echo "Changes detected in ./auth"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/auth:latest ./auth
            docker push ${{ secrets.DOCKER_USERNAME }}/auth:latest
          fi

      - name: Build and push converter image
      - run: |
          if git diff --quiet HEAD -- ./converter; then
            echo "No changes detected in ./converter"
          else
            echo "Changes detected in ./converter"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/converter:latest ./converter
            docker push ${{ secrets.DOCKER_USERNAME }}/converter:latest
          fi
      
      - name: Build and push gateway image
      - run: |
          if git diff --quiet HEAD -- ./gateway; then
            echo "No changes detected in ./gateway"
          else
            echo "Changes detected in ./gateway"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway:latest ./gateway
            docker push ${{ secrets.DOCKER_USERNAME }}/gateway:latest
          fi
